function [q_hist, qd_hist, qdd_hist, x_hist, xdot_hist, x_c_hist, err_hist, tau_hist, Fext_hist] = ...
    simulate_commande_impedance_cercle_contact(robot, q0, qd0, t_vec, x_d, xd_d, xdd_d, ...
                                               Kp_task, Kd_task, Md, Bd, Kd_imp, ...
                                               z_table, Ke_env, Be_env)
% simulate_commande_impedance_cercle_contact reutilise la meme loi
% d'impedance que la partie 5.1, mais avec une trajectoire circulaire
% sous contact.

    [q_hist, qd_hist, qdd_hist, x_hist, xdot_hist, x_c_hist, err_hist, tau_hist, Fext_hist] = ...
        simulate_commande_impedance_verticale(robot, q0, qd0, t_vec, x_d, xd_d, xdd_d, ...
                                              Kp_task, Kd_task, Md, Bd, Kd_imp, ...
                                              z_table, Ke_env, Be_env);
end